name: Deploy user service

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    outputs:
      img-tag: ${{ steps.tag.outputs.this }}

    steps:
      - name: 컨테이너 tag 를 생성한다
        id: tag
        run: >-
          echo "this=$(date +'%y%m%d%H%M')-${GITHUB_SHA:0:4}-dev"
          >> "$GITHUB_OUTPUT"

      - name: 코드를 받아온다
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: corretto
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew app-user:build -x test --stacktrace

      - name: AWS credentials 를 구성한다
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: ECR login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: buildx를 설정한다
        uses: docker/setup-buildx-action@v3

      - name: 컨테이너 이미지를 빌드하고 푸시한다
        env:
          img-uri: ${{ steps.login-ecr.outputs.registry }}/app-user-service
          img-tag: ${{ steps.tag.outputs.this }}
        uses: docker/build-push-action@v4
        with:
          tags: ${{ env.img-uri }}:${{ env.img-tag }}
          push: true
#          cache-from: type=registry,ref=${{ env.img-uri }}:cache
#          cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{ env.img-uri }}:cache
          context: app-user
          file: app-user/Dockerfile
      - name: 이미지 태그를 출력한다
        env:
          img-tag: ${{ steps.tag.outputs.this }}
        run: |
          echo "# 이미지 태그" >> $GITHUB_STEP_SUMMARY
          echo "tag: \`${{ env.img-tag }}\`" >> $GITHUB_STEP_SUMMARY
